framework:
    secret: 'dev'
    form: true
    http_method_override: false
    csrf_protection: true
    validation: true
    translator:
        default_path: '%kernel.project_dir%/translations'
    session:
        storage_factory_id: session.storage.factory.mock_file
    mailer:
        dsn: 'null://null'
