<?php

declare(strict_types=1);

use Symfony\Component\Yaml\Yaml;

require __DIR__.'/../vendor/autoload.php';

$skeletonDir = '/workspace/skeleton';
$routesFile = $skeletonDir.'/routes.yaml';
$target = '/workspace/src/PhpStorm/GeneratedSkeletonController.php';

if (!\is_file($routesFile)) {
    throw new RuntimeException(\sprintf('Routes file not found: %s', $routesFile));
}

/** @var array<string, array{config?: array<string, mixed>}> $routes */
$routes = Yaml::parseFile($routesFile);
\ksort($routes);

\is_dir(\dirname($target)) || \mkdir(\dirname($target), 0777, true);
\file_put_contents($target, renderController($routes));

echo \sprintf("Generated %s\n", $target);

/**
 * @param array<string, array{config?: array<string, mixed>}> $routes
 */
function renderController(array $routes): string
{
    $methods = [];

    foreach ($routes as $name => $route) {
        $config = $route['config'] ?? [];
        if (!\is_array($config) || !isset($config['path'])) {
            continue;
        }

        $methods[] = renderMethod($name, $config);
    }

    $methodsBlock = \implode("\n\n", $methods);

    return <<<PHP
<?php

declare(strict_types=1);

namespace App\\PhpStorm;

use Symfony\\Component\\HttpFoundation\\Response;
use Symfony\\Component\\Routing\\Attribute\\Route;

/**
 * Generated by tools/generate-phpstorm-skeleton-controller.php from /workspace/skeleton/routes.yaml.
 */
final class GeneratedSkeletonController
{
$methodsBlock
}

PHP;
}

/**
 * @param array<string, mixed> $config
 */
function renderMethod(string $name, array $config): string
{
    $arguments = ["name: ".exportValue($name)];

    foreach (['path', 'defaults', 'requirements', 'host', 'schemes', 'methods', 'condition', 'priority', 'env', 'format', 'utf8', 'stateless'] as $key) {
        if (\array_key_exists($key, $config)) {
            $arguments[] = $key.': '.exportValue($config[$key]);
        }
    }

    $parameters = [];
    foreach (methodParameters($config) as $parameter) {
        $parameters[] = renderParameter($parameter);
    }

    $methodName = methodName($name);
    $signature = [] === $parameters ? '' : \implode(', ', $parameters);
    $attribute = '#[Route('.\implode(', ', $arguments).')]';

    return <<<PHP
    $attribute
    public function $methodName($signature): Response
    {
        return new Response();
    }
PHP;
}

function methodName(string $routeName): string
{
    $name = \preg_replace('/[^a-zA-Z0-9]+/', ' ', $routeName) ?? $routeName;
    $name = \str_replace(' ', '', \ucwords(\trim($name)));
    $name = '' === $name ? 'generatedRoute' : \lcfirst($name);

    if (\is_numeric($name[0])) {
        $name = 'route'.$name;
    }

    return $name;
}

/**
 * @param array<string, mixed> $config
 *
 * @return array<int, array{name: string, default: mixed, hasDefault: bool}>
 */
function methodParameters(array $config): array
{
    $names = [];
    foreach ((array) ($config['path'] ?? []) as $path) {
        if (!\is_string($path)) {
            continue;
        }

        if (\preg_match_all('/\{([A-Za-z_][A-Za-z0-9_]*)\}/', $path, $matches)) {
            foreach ($matches[1] as $match) {
                $names[$match] = true;
            }
        }
    }

    $defaults = \is_array($config['defaults'] ?? null) ? $config['defaults'] : [];
    $parameters = [];

    foreach (\array_keys($names) as $name) {
        $parameters[] = [
            'name' => $name,
            'default' => $defaults[$name] ?? null,
            'hasDefault' => \array_key_exists($name, $defaults),
        ];
    }

    \usort($parameters, static function (array $left, array $right): int {
        return ($left['hasDefault'] <=> $right['hasDefault']) ?: 0;
    });

    return $parameters;
}

/**
 * @param array{name: string, default: mixed, hasDefault: bool} $parameter
 */
function renderParameter(array $parameter): string
{
    $name = '$'.$parameter['name'];
    if (!$parameter['hasDefault']) {
        return 'string '.$name;
    }

    $default = $parameter['default'];
    if (\is_int($default)) {
        return 'int '.$name.' = '.exportValue($default);
    }
    if (\is_bool($default)) {
        return 'bool '.$name.' = '.exportValue($default);
    }
    if (null === $default) {
        return '?string '.$name.' = null';
    }

    return 'string '.$name.' = '.exportValue((string) $default);
}

function exportValue(mixed $value): string
{
    if (\is_array($value)) {
        return shortArray($value);
    }

    return \var_export($value, true);
}

/**
 * @param array<mixed> $array
 */
function shortArray(array $array): string
{
    $items = [];
    foreach ($array as $key => $value) {
        $renderedValue = \is_array($value) ? shortArray($value) : \var_export($value, true);

        if (\is_int($key)) {
            $items[] = $renderedValue;
            continue;
        }

        $items[] = \var_export($key, true).' => '.$renderedValue;
    }

    return '['.\implode(', ', $items).']';
}
